### ISSUE TITLE
Add to README.md

### ISSUE THREAD

**Issue by ShubhamJagtap2000** [Noovolari/awesome-cloudops#14]
Hello contributor/s,

Can we add Git/GitOps to the list, also Docker could be added with good resources?

Please provide feedback. Thanks.

**Comment by andreacavagna01** [comment]
HI @ShubhamJagtap2000, Do you mean to have a section dedicated to the Hit and GitOps tools? 

I'm working on a better solution to add data to the awesome list by working on JSON or YAML instead of just the README. 

I'm always open to new ways to manage the list, if you have better ideas please provide a detailed solution and I will try to accommodate :D

**Comment by ShubhamJagtap2000** [comment]
Hi @andreacavagna01, yes we can add a topic for Git and GitOps. Also, your idea sounds good, please add it to the repo by working on JSON/YAML, I will be eager to look after it too. Thanks.

**Comment by urz9999** [comment]
Added a Github and GitOps section, as well as a Docker one. You can find them under Resource Category. Fill free to add content as your heart desires. Kudos!
